name: "Build and deploy"
on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Cache Node dependencies"
        uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Cache dist folder"
        id: astro-cache-dist
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-astro-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-astro-build-

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: npm run build
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          MATOMO_URL: ${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}

      - name: Deploy to Server via ssh key
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: whoami
